const mongoose = require("mongoose");
const { maintenanceDB } = require("../database/database");

// Reusing your product schema for the template
const builtyProductSchema = new mongoose.Schema(
  {
    productName: { type: String, trim: true },
    quantity: { type: Number, default: 0 },
    unit: { type: String, trim: true },
    bagSize: { type: Number },
    totalBags: { type: Number },
    remarks: { type: String, trim: true },
  },
  { _id: false }
);

const builtyTemplateSchema = new mongoose.Schema(
  {
    templateName: { type: String, required: true, trim: true }, 
    date: { type: Date },
    consignerName: { type: String, trim: true },
    consignerContactNumber: { type: String, trim: true },
    consigneeName: { type: String, trim: true },
    consigneeContactNumber: { type: String, trim: true },
    destinationLocation: { type: String, trim: true },
    pickupLocation: { type: String, trim: true },
    pickupLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location" },
    destinationLocationId: { type: mongoose.Schema.Types.ObjectId, ref: "Location" },
    vehicleOwnership: { type: String, enum: ["self", "market"] },
    transportRateAmount: { type: Number, default: 0 },
    transportRateType: { type: String, enum: ["fixed", "per_ton", "per_quintal"] },
    shortageDeductionRate: { type: Number, default: 0 },
    description: { type: String },
    vendorType: { type: String },
    bookingMode: { type: String, enum: ["transporter", "self"] },
    transporterId: { type: mongoose.Schema.Types.ObjectId, ref: "Transporter" },
    commissionAgentId: { type: mongoose.Schema.Types.ObjectId, ref: "CommissionAgent" },
    commissionAgentAmount: { type: Number },
    vehicleId: { type: mongoose.Schema.Types.ObjectId, ref: "VehicleMaster" },
    vendorId: { type: mongoose.Schema.Types.ObjectId, ref: "Vendor" },
    vehicleNumber: { type: String, uppercase: true, trim: true },
    grossVehicleWeight: { type: Number },
    advanceMode: { type: String, enum: ["cash", "fuel", "cash_fuel", "upi", "bank_transfer", "other"] },
    advanceAmount: { type: Number, default: 0 },
    advanceDieselLiters: { type: Number, default: 0 },
    permittedGVW: { type: Number },
    tareWeight: { type: Number },
    grossWeight: { type: Number },
    discountWeight: { type: Number, default: 0 },
    loadingEmptyWeight: { type: Number },
    loadingLoadedWeight: { type: Number },
    loadingMaterialWeight: { type: Number },
    deliveryLoadedWeight: { type: Number },
    deliveryEmptyWeight: { type: Number },
    deliveryMaterialWeight: { type: Number },
    products: [builtyProductSchema],
    status: { type: String, enum: ["Created", "Dispatched", "Completed", "Cancelled"], default: "Created" },
    paymentStatus: { type: String, enum: ["Pending", "Partial", "Completed"], default: "Pending" },
    bagType: { type: String, enum: ["Plastic", "Jute"] },
    bagWeight: { type: Number, min: 0 },
    docNo: { type: String, trim: true },
    cancelReason: { type: String, trim: true },
    completedAt: { type: Date },
    cancelledAt: { type: Date },
    supervisorId: { type: mongoose.Schema.Types.ObjectId },
    driverId: { type: mongoose.Schema.Types.ObjectId, ref: "Driver" },
    consignerId: { type: mongoose.Schema.Types.ObjectId, ref: "Consignor" },
    consigneeId: { type: mongoose.Schema.Types.ObjectId, ref: "Consignee" },
    supervisorModel: { type: String, enum: ["School", "Branch", "BranchGroup"] },
    deliveryStatus: { type: String, enum: ["Delivered", "Less Delivered"] },
    paymentCutAmount: { type: Number },
    dispatchDate: { type: Date },
    startOdometerReading: { type: Number, default: 0 },
    weightPerBag: { type: Number, default: 0 },
    numberOfBags: { type: Number, default: 0 },
    tareWeightUnit: { type: String, enum: ["KG", "Qtl", "MT"] },
    grossWeightUnit: { type: String, enum: ["KG", "Qtl", "MT"] },
    netWeight: { type: Number, default: 0 },
    freightRate: { type: Number, default: 0 },
    freightRateUnit: { type: String, enum: ["KG", "Qtl", "MT", "Bag"] },
    fareAmount: { type: Number, default: 0 },
    fareAmountAdvance: { type: Number, default: 0 },
    loadKataCharge: { type: Number, default: 0 },
    unLoadingCharge: { type: Number, default: 0 },
    unLoadKataCharge: { type: Number, default: 0 },
    loadingCharge: { type: Number, default: 0 },
    isLessDelivered: { type: Boolean, default: false },
    vehicleExpenseAmount: { type: Number },
    createdBy: { type: mongoose.Schema.Types.ObjectId },
    driverCommissionType: { type: String, enum: ["none", "percentage", "fixed"], default: "none" },
    driverCommissionPercentage: { type: Number },
    driverCommissionAmount: { type: Number, default: 0 },
    createdByRole: { type: String },
    workerId: { type: mongoose.Schema.Types.ObjectId }
  },
  { timestamps: true }
);

module.exports = maintenanceDB.model("BuiltyTemplate", builtyTemplateSchema);